name: Expensive

on:
  schedule:
    - cron:  '*/3 * * * *'

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    # Build & Test runs on all platforms
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install system dependencies
        run: |
          echo foo
          ./planet-windwanderer